由用户 iyourcar 启动
构建中 在工作空间 /Users/duncy/.jenkins/workspace/lottery_minprogram 中
 > git rev-parse --is-inside-work-tree # timeout=10
Fetching changes from the remote Git repository
 > git config remote.origin.url http://gitlab.repos.suv163.com/webh5/lottery.git # timeout=10
Fetching upstream changes from http://gitlab.repos.suv163.com/webh5/lottery.git
 > git --version # timeout=10
using GIT_ASKPASS to set credentials 
 > git fetch --tags --progress http://gitlab.repos.suv163.com/webh5/lottery.git +refs/heads/*:refs/remotes/origin/*
 > git rev-parse refs/remotes/origin/develop^{commit} # timeout=10
 > git rev-parse refs/remotes/origin/origin/develop^{commit} # timeout=10
Checking out Revision f1233fbbf0ab32ef1b0707523c33b32a43a1c959 (refs/remotes/origin/develop)
 > git config core.sparsecheckout # timeout=10
 > git checkout -f f1233fbbf0ab32ef1b0707523c33b32a43a1c959
Commit message: "Merge branch 'dev-lxl' into 'develop'"
 > git rev-list --no-walk 2f667b7cff793554459b899480322327681955ba # timeout=10
No emails were triggered.
[lottery_minprogram] $ /bin/bash /var/folders/qk/yjc99frs5717m6nscn9cld7c0000gn/T/jenkins1493917049098344136.sh
builddev
v07.16.15.12
yarn install v1.9.2
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/4] Resolving packages...
success Already up-to-date.
Done in 0.74s.
yarn run v1.9.2
$ cross-env NODE_ENV=dev webpack -p
Hash: b5cf279041b94ba71be6
Version: webpack 2.7.0
Time: 12797ms
                                                                                                      Asset       Size  Chunks                    Chunk Names
                                                                       custom_components/navbar/navbar.wxml  949 bytes          [emitted]         
                                                                                                 ./app.json     2.8 kB          [emitted]         
                                               collect_clues_pages/pages/evalute_result/evalute_result.json  211 bytes          [emitted]         
                                               collect_clues_pages/pages/inquiry_result/inquiry_result.json  308 bytes          [emitted]         
                                           collect_clues_pages/pages/recommend_series/recommend_series.json  309 bytes          [emitted]         
                                             collect_clues_pages/pages/select_car_info/select_car_info.json  209 bytes          [emitted]         
                                                           custom_components/alphabet-nav/alphabet-nav.json   23 bytes          [emitted]         
                                                               custom_components/car_select/car_select.json  102 bytes          [emitted]         
                                                           custom_components/group_detail/group_detail.json   27 bytes          [emitted]         
                                   custom_components/join_welfare_group_entry/join_welfare_group_entry.json   23 bytes          [emitted]         
                                           custom_components/layer-of-cancel-bind/layer-of-cancel-bind.json   23 bytes          [emitted]         
                                                       custom_components/layer-of-guide/layer-of-guide.json   23 bytes          [emitted]         
                                                   custom_components/layer-of-red-bag/layer-of-red-bag.json   23 bytes          [emitted]         
                                                                       custom_components/navbar/navbar.json   25 bytes          [emitted]         
                                                                 custom_components/posters-layer/index.json   23 bytes          [emitted]         
                                           custom_components/prise-activity-alert/prise-activity-alert.json   25 bytes          [emitted]         
                                                         custom_components/trophy_detail/trophy_detail.json   23 bytes          [emitted]         
                                                                   custom_components/userinfo/userinfo.json   23 bytes          [emitted]         
                                                     custom_components/vertion-control/vertion-control.json   25 bytes          [emitted]         
                                             custom_components/visitor-blank-layer/visitor-blank-layer.json   23 bytes          [emitted]         
                                                                                 pages/fill_in/fill_in.json  175 bytes          [emitted]         
                                                         pages/lottery_person_home/lottery_person_home.json  517 bytes          [emitted]         
                                                         pages/strategy/components/imageShow/imageShow.json   23 bytes          [emitted]         
                                                             pages/strategy/components/problem/problem.json   23 bytes          [emitted]         
                                                             pages/strategy/components/service/service.json   23 bytes          [emitted]         
                                                                               pages/strategy/strategy.json  481 bytes          [emitted]         
                                                                                 pages/webview/webview.json  206 bytes          [emitted]         
                                                                          pages/welfare_home/item/item.json   23 bytes          [emitted]         
                                                                       pages/welfare_home/welfare_home.json  708 bytes          [emitted]         
                      welfare_extand_pages/custom-components/activity-description/activity-description.json   23 bytes          [emitted]         
                                    welfare_extand_pages/custom-components/activity-list/activity-list.json   25 bytes          [emitted]         
         welfare_extand_pages/custom-components/get_welfare_banner/get_welfare_alert/get_welfare_alert.json   23 bytes          [emitted]         
                          welfare_extand_pages/custom-components/get_welfare_banner/get_welfare_banner.json  348 bytes          [emitted]         
         welfare_extand_pages/custom-components/get_welfare_banner/get_welfare_goods/get_welfare_goods.json   23 bytes          [emitted]         
       welfare_extand_pages/custom-components/get_welfare_banner/get_welfare_people/get_welfare_people.json   23 bytes          [emitted]         
   welfare_extand_pages/custom-components/get_welfare_banner/get_welfare_progress/get_welfare_progress.json   23 bytes          [emitted]         
                                      welfare_extand_pages/custom-components/go-home-icon/go-home-icon.json   23 bytes          [emitted]         
                                        welfare_extand_pages/custom-components/go-top-icon/go-top-icon.json   23 bytes          [emitted]         
                                          welfare_extand_pages/custom-components/goods-item/goods-item.json   23 bytes          [emitted]         
                                                    welfare_extand_pages/custom-components/guide/guide.json   23 bytes          [emitted]         
                                            welfare_extand_pages/custom-components/just-time/just-time.json   23 bytes          [emitted]         
                    welfare_extand_pages/custom-components/layer-of-add-customer/layer-of-add-customer.json   23 bytes          [emitted]         
                      welfare_extand_pages/custom-components/layer-of-bind-taobao/layer-of-bind-taobao.json   23 bytes          [emitted]         
              welfare_extand_pages/custom-components/layer-of-cashback-status/layer-of-cashback-status.json   23 bytes          [emitted]         
welfare_extand_pages/custom-components/layer-of-check-cancel-subscribe/layer-of-check-cancel-subscribe.json   23 bytes          [emitted]         
        welfare_extand_pages/custom-components/layer-of-check-order-status/layer-of-check-order-status.json   23 bytes          [emitted]         
                    welfare_extand_pages/custom-components/layer-of-copy-orderid/layer-of-copy-orderid.json   23 bytes          [emitted]         
    welfare_extand_pages/custom-components/layer-of-creat-poster-success/layer-of-creat-poster-success.json   23 bytes          [emitted]         
                    welfare_extand_pages/custom-components/layer-of-creat-poster/layer-of-creat-poster.json   23 bytes          [emitted]         
                    welfare_extand_pages/custom-components/layer-of-limit-number/layer-of-limit-number.json   23 bytes          [emitted]         
                          welfare_extand_pages/custom-components/layer-of-null-card/layer-of-null-card.json   23 bytes          [emitted]         
                            welfare_extand_pages/custom-components/layer-of-only-one/layer-of-only-one.json   23 bytes          [emitted]         
                      welfare_extand_pages/custom-components/layer-of-order-check/layer-of-order-check.json   23 bytes          [emitted]         
                                    welfare_extand_pages/custom-components/layer-of-rule/layer-of-rule.json   23 bytes          [emitted]         
                    welfare_extand_pages/custom-components/layer-of-select-order/layer-of-select-order.json   23 bytes          [emitted]         
                                  welfare_extand_pages/custom-components/layer-of-share/layer-of-share.json   23 bytes          [emitted]         
              welfare_extand_pages/custom-components/layer-of-tao-key-success/layer-of-tao-key-success.json   23 bytes          [emitted]         
                                      welfare_extand_pages/custom-components/more-welfare/more-welfare.json  162 bytes          [emitted]         
welfare_extand_pages/custom-components/official_customer_service_entry/official_customer_service_entry.json  129 bytes          [emitted]         
                                    welfare_extand_pages/custom-components/order-process/order-process.json   23 bytes          [emitted]         
                            welfare_extand_pages/custom-components/rank-and-strategy/rank-and-strategy.json   23 bytes          [emitted]         
                                          welfare_extand_pages/custom-components/unverified/unverified.json   25 bytes          [emitted]         
                            welfare_extand_pages/custom-components/welfare_card_item/welfare_card_item.json   25 bytes          [emitted]         
                                                                  welfare_extand_pages/pages/base/base.json  210 bytes          [emitted]         
                                                welfare_extand_pages/pages/bounty_detail/bounty_detail.json  445 bytes          [emitted]         
                                              welfare_extand_pages/pages/cashback_apply/cashback_apply.json    1.09 kB          [emitted]         
                              welfare_extand_pages/pages/cashback_apply_success/cashback_apply_success.json     1.1 kB          [emitted]         
                                            welfare_extand_pages/pages/cashback_record/cashback_record.json  188 bytes          [emitted]         
                                                welfare_extand_pages/pages/copy_own_code/copy_own_code.json  258 bytes          [emitted]         
                                  welfare_extand_pages/pages/fans_activity_detail/fans_activity_detail.json  234 bytes          [emitted]         
                                        welfare_extand_pages/pages/fans_activity_get/fans_activity_get.json  384 bytes          [emitted]         
                                  welfare_extand_pages/pages/fans_activity_record/fans_activity_record.json  128 bytes          [emitted]         
                                                        welfare_extand_pages/pages/fill_info/fill_info.json  190 bytes          [emitted]         
                                        welfare_extand_pages/pages/fill_info_success/fill_info_success.json  190 bytes          [emitted]         
                                                      welfare_extand_pages/pages/get_bounty/get_bounty.json    1.14 kB          [emitted]         
                                                    welfare_extand_pages/pages/get_welfare/get_welfare.json  669 bytes          [emitted]         
                                      welfare_extand_pages/pages/join-welfare-group/join-welfare-group.json  131 bytes          [emitted]         
                                       welfare_extand_pages/pages/lottery_record/award_item/award_item.json   23 bytes          [emitted]         
                                   welfare_extand_pages/pages/lottery_record/history_item/history_item.json   23 bytes          [emitted]         
                                              welfare_extand_pages/pages/lottery_record/lottery_record.json  410 bytes          [emitted]         
                                                              welfare_extand_pages/pages/reward/reward.json  531 bytes          [emitted]         
                                                    welfare_extand_pages/pages/reward_list/reward_list.json  347 bytes          [emitted]         
                                                      welfare_extand_pages/pages/set_remind/set_remind.json  269 bytes          [emitted]         
                                                          welfare_extand_pages/pages/update_page/index.json  209 bytes          [emitted]         
                                        welfare_extand_pages/pages/welfare_card_list/welfare_card_list.json  302 bytes          [emitted]         
                                              welfare_extand_pages/pages/welfare_detail/welfare_detail.json    2.12 kB          [emitted]         
                                                                                                 ./app.wxss    20.4 kB          [emitted]         
                                                   collect_clues_pages/pages/collect_clue/collect_clue.wxss    2.57 kB          [emitted]         
                                               collect_clues_pages/pages/evalute_result/evalute_result.wxss    1.31 kB          [emitted]         
                                               collect_clues_pages/pages/inquiry_result/inquiry_result.wxss    3.48 kB          [emitted]         
                                           collect_clues_pages/pages/recommend_series/recommend_series.wxss    7.99 kB          [emitted]         
                                             collect_clues_pages/pages/select_car_info/select_car_info.wxss    3.83 kB          [emitted]         
                                                           custom_components/alphabet-nav/alphabet-nav.wxss  898 bytes          [emitted]         
                                                               custom_components/car_select/car_select.wxss    3.01 kB          [emitted]         
                                                           custom_components/group_detail/group_detail.wxss    2.69 kB          [emitted]         
                                   custom_components/join_welfare_group_entry/join_welfare_group_entry.wxss    1.61 kB          [emitted]         
                                           custom_components/layer-of-cancel-bind/layer-of-cancel-bind.wxss    1.89 kB          [emitted]         
                                                       custom_components/layer-of-guide/layer-of-guide.wxss    2.02 kB          [emitted]         
                                                   custom_components/layer-of-red-bag/layer-of-red-bag.wxss    6.51 kB          [emitted]         
                                                                       custom_components/navbar/navbar.wxss    2.09 kB          [emitted]         
                                                                 custom_components/posters-layer/index.wxss   57 bytes          [emitted]         
                                           custom_components/prise-activity-alert/prise-activity-alert.wxss    1.75 kB          [emitted]         
                                                         custom_components/trophy_detail/trophy_detail.wxss    3.11 kB          [emitted]         
                                                                   custom_components/userinfo/userinfo.wxss    1.63 kB          [emitted]         
                                                     custom_components/vertion-control/vertion-control.wxss    2.31 kB          [emitted]         
                                             custom_components/visitor-blank-layer/visitor-blank-layer.wxss  931 bytes          [emitted]         
                                                                                 pages/fill_in/fill_in.wxss       4 kB          [emitted]         
                                                         pages/lottery_person_home/lottery_person_home.wxss    4.35 kB          [emitted]         
                                                         pages/strategy/components/imageShow/imageShow.wxss  822 bytes          [emitted]         
                                                             pages/strategy/components/problem/problem.wxss    1.44 kB          [emitted]         
                                                             pages/strategy/components/service/service.wxss    1.41 kB          [emitted]         
                                                                               pages/strategy/strategy.wxss    1.61 kB          [emitted]         
                                                                                 pages/webview/webview.wxss  799 bytes          [emitted]         
                                                                          pages/welfare_home/item/item.wxss     8.4 kB          [emitted]         
                                                                       pages/welfare_home/welfare_home.wxss    4.46 kB          [emitted]         
                      welfare_extand_pages/custom-components/activity-description/activity-description.wxss    1.91 kB          [emitted]         
                                    welfare_extand_pages/custom-components/activity-list/activity-list.wxss    4.79 kB          [emitted]         
         welfare_extand_pages/custom-components/get_welfare_banner/get_welfare_alert/get_welfare_alert.wxss    2.73 kB          [emitted]         
                          welfare_extand_pages/custom-components/get_welfare_banner/get_welfare_banner.wxss    1.12 kB          [emitted]         
         welfare_extand_pages/custom-components/get_welfare_banner/get_welfare_goods/get_welfare_goods.wxss    2.39 kB          [emitted]         
       welfare_extand_pages/custom-components/get_welfare_banner/get_welfare_people/get_welfare_people.wxss  905 bytes          [emitted]         
   welfare_extand_pages/custom-components/get_welfare_banner/get_welfare_progress/get_welfare_progress.wxss  681 bytes          [emitted]         
                                      welfare_extand_pages/custom-components/go-home-icon/go-home-icon.wxss    1.01 kB          [emitted]         
                                        welfare_extand_pages/custom-components/go-top-icon/go-top-icon.wxss    1.39 kB          [emitted]         
                                          welfare_extand_pages/custom-components/goods-item/goods-item.wxss     5.4 kB          [emitted]         
                                                    welfare_extand_pages/custom-components/guide/guide.wxss     1.4 kB          [emitted]         
                                            welfare_extand_pages/custom-components/just-time/just-time.wxss    1.41 kB          [emitted]         
                    welfare_extand_pages/custom-components/layer-of-add-customer/layer-of-add-customer.wxss    2.64 kB          [emitted]         
                      welfare_extand_pages/custom-components/layer-of-bind-taobao/layer-of-bind-taobao.wxss    2.73 kB          [emitted]         
              welfare_extand_pages/custom-components/layer-of-cashback-status/layer-of-cashback-status.wxss    1.81 kB          [emitted]         
welfare_extand_pages/custom-components/layer-of-check-cancel-subscribe/layer-of-check-cancel-subscribe.wxss    1.86 kB          [emitted]         
        welfare_extand_pages/custom-components/layer-of-check-order-status/layer-of-check-order-status.wxss    2.87 kB          [emitted]         
                    welfare_extand_pages/custom-components/layer-of-copy-orderid/layer-of-copy-orderid.wxss       2 kB          [emitted]         
    welfare_extand_pages/custom-components/layer-of-creat-poster-success/layer-of-creat-poster-success.wxss    2.16 kB          [emitted]         
                    welfare_extand_pages/custom-components/layer-of-creat-poster/layer-of-creat-poster.wxss    4.32 kB          [emitted]         
                    welfare_extand_pages/custom-components/layer-of-limit-number/layer-of-limit-number.wxss    1.91 kB          [emitted]         
                          welfare_extand_pages/custom-components/layer-of-null-card/layer-of-null-card.wxss    2.04 kB          [emitted]         
                            welfare_extand_pages/custom-components/layer-of-only-one/layer-of-only-one.wxss    1.89 kB          [emitted]         
                      welfare_extand_pages/custom-components/layer-of-order-check/layer-of-order-check.wxss    3.11 kB          [emitted]         
                                    welfare_extand_pages/custom-components/layer-of-rule/layer-of-rule.wxss    1.96 kB          [emitted]         
                    welfare_extand_pages/custom-components/layer-of-select-order/layer-of-select-order.wxss     2.9 kB          [emitted]         
                                  welfare_extand_pages/custom-components/layer-of-share/layer-of-share.wxss    2.78 kB          [emitted]         
              welfare_extand_pages/custom-components/layer-of-tao-key-success/layer-of-tao-key-success.wxss    1.82 kB          [emitted]         
                                      welfare_extand_pages/custom-components/more-welfare/more-welfare.wxss    6.86 kB          [emitted]         
welfare_extand_pages/custom-components/official_customer_service_entry/official_customer_service_entry.wxss    1.67 kB          [emitted]         
                                    welfare_extand_pages/custom-components/order-process/order-process.wxss    2.64 kB          [emitted]         
                            welfare_extand_pages/custom-components/rank-and-strategy/rank-and-strategy.wxss    4.74 kB          [emitted]         
                                          welfare_extand_pages/custom-components/unverified/unverified.wxss     7.2 kB          [emitted]         
                            welfare_extand_pages/custom-components/welfare_card_item/welfare_card_item.wxss    2.18 kB          [emitted]         
                                                                  welfare_extand_pages/pages/base/base.wxss  850 bytes          [emitted]         
                                                welfare_extand_pages/pages/bounty_detail/bounty_detail.wxss     5.4 kB          [emitted]         
                                              welfare_extand_pages/pages/cashback_apply/cashback_apply.wxss    4.83 kB          [emitted]         
                              welfare_extand_pages/pages/cashback_apply_success/cashback_apply_success.wxss    5.18 kB          [emitted]         
                                            welfare_extand_pages/pages/cashback_record/cashback_record.wxss    2.13 kB          [emitted]         
                                                welfare_extand_pages/pages/copy_own_code/copy_own_code.wxss    2.57 kB          [emitted]         
                                  welfare_extand_pages/pages/fans_activity_detail/fans_activity_detail.wxss    1.93 kB          [emitted]         
                                        welfare_extand_pages/pages/fans_activity_get/fans_activity_get.wxss    1.63 kB          [emitted]         
                                  welfare_extand_pages/pages/fans_activity_record/fans_activity_record.wxss     2.3 kB          [emitted]         
                                                        welfare_extand_pages/pages/fill_info/fill_info.wxss    2.45 kB          [emitted]         
                                        welfare_extand_pages/pages/fill_info_success/fill_info_success.wxss    2.03 kB          [emitted]         
                                                      welfare_extand_pages/pages/get_bounty/get_bounty.wxss    7.18 kB          [emitted]         
                                                    welfare_extand_pages/pages/get_welfare/get_welfare.wxss  850 bytes          [emitted]         
                                      welfare_extand_pages/pages/join-welfare-group/join-welfare-group.wxss    2.11 kB          [emitted]         
                                       welfare_extand_pages/pages/lottery_record/award_item/award_item.wxss    1.67 kB          [emitted]         
                                   welfare_extand_pages/pages/lottery_record/history_item/history_item.wxss    2.04 kB          [emitted]         
                                              welfare_extand_pages/pages/lottery_record/lottery_record.wxss    6.58 kB          [emitted]         
                                                              welfare_extand_pages/pages/reward/reward.wxss    3.71 kB          [emitted]         
                                                    welfare_extand_pages/pages/reward_list/reward_list.wxss    3.19 kB          [emitted]         
                                                      welfare_extand_pages/pages/set_remind/set_remind.wxss    4.83 kB          [emitted]         
                                                          welfare_extand_pages/pages/update_page/index.wxss  828 bytes          [emitted]         
                                        welfare_extand_pages/pages/welfare_card_list/welfare_card_list.wxss    1.38 kB          [emitted]         
                                              welfare_extand_pages/pages/welfare_detail/welfare_detail.wxss    16.8 kB          [emitted]         
                                                   collect_clues_pages/pages/collect_clue/collect_clue.wxml    2.33 kB          [emitted]         
                                               collect_clues_pages/pages/evalute_result/evalute_result.wxml  903 bytes          [emitted]         
                                               collect_clues_pages/pages/inquiry_result/inquiry_result.wxml    1.92 kB          [emitted]         
                                           collect_clues_pages/pages/recommend_series/recommend_series.wxml    4.54 kB          [emitted]         
                                             collect_clues_pages/pages/select_car_info/select_car_info.wxml    1.97 kB          [emitted]         
                                                           custom_components/alphabet-nav/alphabet-nav.wxml  614 bytes          [emitted]         
                                                               custom_components/car_select/car_select.wxml    3.94 kB          [emitted]         
                                                           custom_components/group_detail/group_detail.wxml     1.2 kB          [emitted]         
                                   custom_components/join_welfare_group_entry/join_welfare_group_entry.wxml  638 bytes          [emitted]         
                                           custom_components/layer-of-cancel-bind/layer-of-cancel-bind.wxml  559 bytes          [emitted]         
                                                       custom_components/layer-of-guide/layer-of-guide.wxml  967 bytes          [emitted]         
                                                   custom_components/layer-of-red-bag/layer-of-red-bag.wxml    1.41 kB          [emitted]         
                                                   collect_clues_pages/pages/collect_clue/collect_clue.json  314 bytes          [emitted]         
                                           custom_components/prise-activity-alert/prise-activity-alert.wxml    2.63 kB          [emitted]         
                                                         custom_components/trophy_detail/trophy_detail.wxml    1.06 kB          [emitted]         
                                                                   custom_components/userinfo/userinfo.wxml  473 bytes          [emitted]         
                                                     custom_components/vertion-control/vertion-control.wxml    1.01 kB          [emitted]         
                                             custom_components/visitor-blank-layer/visitor-blank-layer.wxml  112 bytes          [emitted]         
                                                                                 pages/fill_in/fill_in.wxml    3.95 kB          [emitted]         
                                                         pages/lottery_person_home/lottery_person_home.wxml    2.68 kB          [emitted]         
                                                         pages/strategy/components/imageShow/imageShow.wxml  168 bytes          [emitted]         
                                                             pages/strategy/components/problem/problem.wxml    1.46 kB          [emitted]         
                                                             pages/strategy/components/service/service.wxml  725 bytes          [emitted]         
                                                                               pages/strategy/strategy.wxml    1.52 kB          [emitted]         
                                                                                 pages/webview/webview.wxml  133 bytes          [emitted]         
                                                                          pages/welfare_home/item/item.wxml    4.88 kB          [emitted]         
                                                                       pages/welfare_home/welfare_home.wxml     5.2 kB          [emitted]         
                      welfare_extand_pages/custom-components/activity-description/activity-description.wxml  370 bytes          [emitted]         
                                    welfare_extand_pages/custom-components/activity-list/activity-list.wxml    6.88 kB          [emitted]         
         welfare_extand_pages/custom-components/get_welfare_banner/get_welfare_alert/get_welfare_alert.wxml     3.8 kB          [emitted]         
                          welfare_extand_pages/custom-components/get_welfare_banner/get_welfare_banner.wxml    1.26 kB          [emitted]         
         welfare_extand_pages/custom-components/get_welfare_banner/get_welfare_goods/get_welfare_goods.wxml    3.61 kB          [emitted]         
       welfare_extand_pages/custom-components/get_welfare_banner/get_welfare_people/get_welfare_people.wxml    1.09 kB          [emitted]         
   welfare_extand_pages/custom-components/get_welfare_banner/get_welfare_progress/get_welfare_progress.wxml  623 bytes          [emitted]         
                                      welfare_extand_pages/custom-components/go-home-icon/go-home-icon.wxml   61 bytes          [emitted]         
                                        welfare_extand_pages/custom-components/go-top-icon/go-top-icon.wxml   74 bytes          [emitted]         
                                          welfare_extand_pages/custom-components/goods-item/goods-item.wxml    3.96 kB          [emitted]         
                                                    welfare_extand_pages/custom-components/guide/guide.wxml    1.75 kB          [emitted]         
                                            welfare_extand_pages/custom-components/just-time/just-time.wxml  591 bytes          [emitted]         
                    welfare_extand_pages/custom-components/layer-of-add-customer/layer-of-add-customer.wxml       2 kB          [emitted]         
                      welfare_extand_pages/custom-components/layer-of-bind-taobao/layer-of-bind-taobao.wxml  831 bytes          [emitted]         
              welfare_extand_pages/custom-components/layer-of-cashback-status/layer-of-cashback-status.wxml  416 bytes          [emitted]         
welfare_extand_pages/custom-components/layer-of-check-cancel-subscribe/layer-of-check-cancel-subscribe.wxml  580 bytes          [emitted]         
        welfare_extand_pages/custom-components/layer-of-check-order-status/layer-of-check-order-status.wxml    1.02 kB          [emitted]         
                    welfare_extand_pages/custom-components/layer-of-copy-orderid/layer-of-copy-orderid.wxml  616 bytes          [emitted]         
    welfare_extand_pages/custom-components/layer-of-creat-poster-success/layer-of-creat-poster-success.wxml  660 bytes          [emitted]         
                    welfare_extand_pages/custom-components/layer-of-creat-poster/layer-of-creat-poster.wxml    1.77 kB          [emitted]         
                    welfare_extand_pages/custom-components/layer-of-limit-number/layer-of-limit-number.wxml  618 bytes          [emitted]         
                          welfare_extand_pages/custom-components/layer-of-null-card/layer-of-null-card.wxml  529 bytes          [emitted]         
                            welfare_extand_pages/custom-components/layer-of-only-one/layer-of-only-one.wxml  595 bytes          [emitted]         
                      welfare_extand_pages/custom-components/layer-of-order-check/layer-of-order-check.wxml    1.32 kB          [emitted]         
                                    welfare_extand_pages/custom-components/layer-of-rule/layer-of-rule.wxml  630 bytes          [emitted]         
                    welfare_extand_pages/custom-components/layer-of-select-order/layer-of-select-order.wxml    1.11 kB          [emitted]         
                                  welfare_extand_pages/custom-components/layer-of-share/layer-of-share.wxml  613 bytes          [emitted]         
              welfare_extand_pages/custom-components/layer-of-tao-key-success/layer-of-tao-key-success.wxml  485 bytes          [emitted]         
                                      welfare_extand_pages/custom-components/more-welfare/more-welfare.wxml    6.69 kB          [emitted]         
welfare_extand_pages/custom-components/official_customer_service_entry/official_customer_service_entry.wxml  579 bytes          [emitted]         
                                    welfare_extand_pages/custom-components/order-process/order-process.wxml  680 bytes          [emitted]         
                            welfare_extand_pages/custom-components/rank-and-strategy/rank-and-strategy.wxml    2.03 kB          [emitted]         
                                          welfare_extand_pages/custom-components/unverified/unverified.wxml  988 bytes          [emitted]         
                            welfare_extand_pages/custom-components/welfare_card_item/welfare_card_item.wxml  420 bytes          [emitted]         
                                                                  welfare_extand_pages/pages/base/base.wxml   36 bytes          [emitted]         
                                                welfare_extand_pages/pages/bounty_detail/bounty_detail.wxml    4.76 kB          [emitted]         
                                              welfare_extand_pages/pages/cashback_apply/cashback_apply.wxml    4.55 kB          [emitted]         
                              welfare_extand_pages/pages/cashback_apply_success/cashback_apply_success.wxml     9.3 kB          [emitted]         
                                            welfare_extand_pages/pages/cashback_record/cashback_record.wxml  983 bytes          [emitted]         
                                                welfare_extand_pages/pages/copy_own_code/copy_own_code.wxml     1.2 kB          [emitted]         
                                  welfare_extand_pages/pages/fans_activity_detail/fans_activity_detail.wxml  879 bytes          [emitted]         
                                        welfare_extand_pages/pages/fans_activity_get/fans_activity_get.wxml  877 bytes          [emitted]         
                                  welfare_extand_pages/pages/fans_activity_record/fans_activity_record.wxml    1.02 kB          [emitted]         
                                                        welfare_extand_pages/pages/fill_info/fill_info.wxml    2.19 kB          [emitted]         
                                        welfare_extand_pages/pages/fill_info_success/fill_info_success.wxml    1.69 kB          [emitted]         
                                                      welfare_extand_pages/pages/get_bounty/get_bounty.wxml    6.51 kB          [emitted]         
                                                    welfare_extand_pages/pages/get_welfare/get_welfare.wxml  830 bytes          [emitted]         
                                      welfare_extand_pages/pages/join-welfare-group/join-welfare-group.wxml    1.15 kB          [emitted]         
                                       welfare_extand_pages/pages/lottery_record/award_item/award_item.wxml  466 bytes          [emitted]         
                                   welfare_extand_pages/pages/lottery_record/history_item/history_item.wxml  917 bytes          [emitted]         
                                              welfare_extand_pages/pages/lottery_record/lottery_record.wxml    3.03 kB          [emitted]         
                                                              welfare_extand_pages/pages/reward/reward.wxml    3.68 kB          [emitted]         
                                                    welfare_extand_pages/pages/reward_list/reward_list.wxml    2.53 kB          [emitted]         
                                                      welfare_extand_pages/pages/set_remind/set_remind.wxml    3.75 kB          [emitted]         
                                                          welfare_extand_pages/pages/update_page/index.wxml    1.04 kB          [emitted]         
                                        welfare_extand_pages/pages/welfare_card_list/welfare_card_list.wxml  849 bytes          [emitted]         
                                              welfare_extand_pages/pages/welfare_detail/welfare_detail.wxml    19.6 kB          [emitted]         
                                                                 custom_components/posters-layer/index.wxml  111 bytes          [emitted]         
                              welfare_extand_pages/custom-components/welfare_card_item/welfare_card_item.js    4.67 kB       1  [emitted]         welfare_extand_pages/custom-components/welfare_card_item/welfare_card_item
           welfare_extand_pages/custom-components/get_welfare_banner/get_welfare_alert/get_welfare_alert.js    5.32 kB       2  [emitted]         welfare_extand_pages/custom-components/get_welfare_banner/get_welfare_alert/get_welfare_alert
                                                                                                     app.js    5.47 kB       3  [emitted]         app
                                                welfare_extand_pages/pages/welfare_detail/welfare_detail.js    12.3 kB       4  [emitted]         welfare_extand_pages/pages/welfare_detail/welfare_detail
                                          welfare_extand_pages/pages/welfare_card_list/welfare_card_list.js    1.25 kB       5  [emitted]         welfare_extand_pages/pages/welfare_card_list/welfare_card_list
                                                            welfare_extand_pages/pages/update_page/index.js  899 bytes       6  [emitted]         welfare_extand_pages/pages/update_page/index
                                                        welfare_extand_pages/pages/set_remind/set_remind.js    2.31 kB       7  [emitted]         welfare_extand_pages/pages/set_remind/set_remind
                                                      welfare_extand_pages/pages/reward_list/reward_list.js    1.75 kB       8  [emitted]         welfare_extand_pages/pages/reward_list/reward_list
                                                                welfare_extand_pages/pages/reward/reward.js    3.41 kB       9  [emitted]         welfare_extand_pages/pages/reward/reward
                                                welfare_extand_pages/pages/lottery_record/lottery_record.js    5.37 kB      10  [emitted]         welfare_extand_pages/pages/lottery_record/lottery_record
                                     welfare_extand_pages/pages/lottery_record/history_item/history_item.js  574 bytes      11  [emitted]         welfare_extand_pages/pages/lottery_record/history_item/history_item
                                         welfare_extand_pages/pages/lottery_record/award_item/award_item.js  587 bytes      12  [emitted]         welfare_extand_pages/pages/lottery_record/award_item/award_item
                                        welfare_extand_pages/pages/join-welfare-group/join-welfare-group.js  857 bytes      13  [emitted]         welfare_extand_pages/pages/join-welfare-group/join-welfare-group
                                                      welfare_extand_pages/pages/get_welfare/get_welfare.js    2.79 kB      14  [emitted]         welfare_extand_pages/pages/get_welfare/get_welfare
                                                        welfare_extand_pages/pages/get_bounty/get_bounty.js    9.33 kB      15  [emitted]         welfare_extand_pages/pages/get_bounty/get_bounty
                                          welfare_extand_pages/pages/fill_info_success/fill_info_success.js  984 bytes      16  [emitted]         welfare_extand_pages/pages/fill_info_success/fill_info_success
                                                          welfare_extand_pages/pages/fill_info/fill_info.js    2.12 kB      17  [emitted]         welfare_extand_pages/pages/fill_info/fill_info
                                    welfare_extand_pages/pages/fans_activity_record/fans_activity_record.js    2.29 kB      18  [emitted]         welfare_extand_pages/pages/fans_activity_record/fans_activity_record
                                          welfare_extand_pages/pages/fans_activity_get/fans_activity_get.js    1.94 kB      19  [emitted]         welfare_extand_pages/pages/fans_activity_get/fans_activity_get
                                    welfare_extand_pages/pages/fans_activity_detail/fans_activity_detail.js    1.73 kB      20  [emitted]         welfare_extand_pages/pages/fans_activity_detail/fans_activity_detail
                                                  welfare_extand_pages/pages/copy_own_code/copy_own_code.js    2.24 kB      21  [emitted]         welfare_extand_pages/pages/copy_own_code/copy_own_code
                                              welfare_extand_pages/pages/cashback_record/cashback_record.js    2.18 kB      22  [emitted]         welfare_extand_pages/pages/cashback_record/cashback_record
                                welfare_extand_pages/pages/cashback_apply_success/cashback_apply_success.js    4.87 kB      23  [emitted]         welfare_extand_pages/pages/cashback_apply_success/cashback_apply_success
                                                welfare_extand_pages/pages/cashback_apply/cashback_apply.js    6.92 kB      24  [emitted]         welfare_extand_pages/pages/cashback_apply/cashback_apply
                                                  welfare_extand_pages/pages/bounty_detail/bounty_detail.js     7.8 kB      25  [emitted]         welfare_extand_pages/pages/bounty_detail/bounty_detail
                                                                    welfare_extand_pages/pages/base/base.js     1.5 kB      26  [emitted]         welfare_extand_pages/pages/base/base
                                            welfare_extand_pages/custom-components/unverified/unverified.js  399 bytes      27  [emitted]         welfare_extand_pages/custom-components/unverified/unverified
                              welfare_extand_pages/custom-components/rank-and-strategy/rank-and-strategy.js    2.29 kB      28  [emitted]         welfare_extand_pages/custom-components/rank-and-strategy/rank-and-strategy
                                      welfare_extand_pages/custom-components/order-process/order-process.js    2.81 kB      29  [emitted]         welfare_extand_pages/custom-components/order-process/order-process
  welfare_extand_pages/custom-components/official_customer_service_entry/official_customer_service_entry.js  467 bytes      30  [emitted]         welfare_extand_pages/custom-components/official_customer_service_entry/official_customer_service_entry
                                        welfare_extand_pages/custom-components/more-welfare/more-welfare.js     2.1 kB      31  [emitted]         welfare_extand_pages/custom-components/more-welfare/more-welfare
                welfare_extand_pages/custom-components/layer-of-tao-key-success/layer-of-tao-key-success.js  338 bytes      32  [emitted]         welfare_extand_pages/custom-components/layer-of-tao-key-success/layer-of-tao-key-success
                                    welfare_extand_pages/custom-components/layer-of-share/layer-of-share.js  450 bytes      33  [emitted]         welfare_extand_pages/custom-components/layer-of-share/layer-of-share
                      welfare_extand_pages/custom-components/layer-of-select-order/layer-of-select-order.js    1.06 kB      34  [emitted]         welfare_extand_pages/custom-components/layer-of-select-order/layer-of-select-order
                                      welfare_extand_pages/custom-components/layer-of-rule/layer-of-rule.js  396 bytes      35  [emitted]         welfare_extand_pages/custom-components/layer-of-rule/layer-of-rule
                        welfare_extand_pages/custom-components/layer-of-order-check/layer-of-order-check.js    2.44 kB      36  [emitted]         welfare_extand_pages/custom-components/layer-of-order-check/layer-of-order-check
                              welfare_extand_pages/custom-components/layer-of-only-one/layer-of-only-one.js  394 bytes      37  [emitted]         welfare_extand_pages/custom-components/layer-of-only-one/layer-of-only-one
                            welfare_extand_pages/custom-components/layer-of-null-card/layer-of-null-card.js  528 bytes      38  [emitted]         welfare_extand_pages/custom-components/layer-of-null-card/layer-of-null-card
                      welfare_extand_pages/custom-components/layer-of-limit-number/layer-of-limit-number.js  400 bytes      39  [emitted]         welfare_extand_pages/custom-components/layer-of-limit-number/layer-of-limit-number
                      welfare_extand_pages/custom-components/layer-of-creat-poster/layer-of-creat-poster.js    1.45 kB      40  [emitted]         welfare_extand_pages/custom-components/layer-of-creat-poster/layer-of-creat-poster
      welfare_extand_pages/custom-components/layer-of-creat-poster-success/layer-of-creat-poster-success.js  521 bytes      41  [emitted]         welfare_extand_pages/custom-components/layer-of-creat-poster-success/layer-of-creat-poster-success
                      welfare_extand_pages/custom-components/layer-of-copy-orderid/layer-of-copy-orderid.js  607 bytes      42  [emitted]         welfare_extand_pages/custom-components/layer-of-copy-orderid/layer-of-copy-orderid
          welfare_extand_pages/custom-components/layer-of-check-order-status/layer-of-check-order-status.js  803 bytes      43  [emitted]         welfare_extand_pages/custom-components/layer-of-check-order-status/layer-of-check-order-status
  welfare_extand_pages/custom-components/layer-of-check-cancel-subscribe/layer-of-check-cancel-subscribe.js  387 bytes      44  [emitted]         welfare_extand_pages/custom-components/layer-of-check-cancel-subscribe/layer-of-check-cancel-subscribe
                welfare_extand_pages/custom-components/layer-of-cashback-status/layer-of-cashback-status.js  353 bytes      45  [emitted]         welfare_extand_pages/custom-components/layer-of-cashback-status/layer-of-cashback-status
                        welfare_extand_pages/custom-components/layer-of-bind-taobao/layer-of-bind-taobao.js  493 bytes      46  [emitted]         welfare_extand_pages/custom-components/layer-of-bind-taobao/layer-of-bind-taobao
                      welfare_extand_pages/custom-components/layer-of-add-customer/layer-of-add-customer.js  543 bytes      47  [emitted]         welfare_extand_pages/custom-components/layer-of-add-customer/layer-of-add-customer
                                              welfare_extand_pages/custom-components/just-time/just-time.js  309 bytes      48  [emitted]         welfare_extand_pages/custom-components/just-time/just-time
                                                      welfare_extand_pages/custom-components/guide/guide.js     1.3 kB      49  [emitted]         welfare_extand_pages/custom-components/guide/guide
                                            welfare_extand_pages/custom-components/goods-item/goods-item.js    2.76 kB      50  [emitted]         welfare_extand_pages/custom-components/goods-item/goods-item
                                          welfare_extand_pages/custom-components/go-top-icon/go-top-icon.js  361 bytes      51  [emitted]         welfare_extand_pages/custom-components/go-top-icon/go-top-icon
                                        welfare_extand_pages/custom-components/go-home-icon/go-home-icon.js  402 bytes      52  [emitted]         welfare_extand_pages/custom-components/go-home-icon/go-home-icon
     welfare_extand_pages/custom-components/get_welfare_banner/get_welfare_progress/get_welfare_progress.js  692 bytes      53  [emitted]         welfare_extand_pages/custom-components/get_welfare_banner/get_welfare_progress/get_welfare_progress
         welfare_extand_pages/custom-components/get_welfare_banner/get_welfare_people/get_welfare_people.js  927 bytes      54  [emitted]         welfare_extand_pages/custom-components/get_welfare_banner/get_welfare_people/get_welfare_people
           welfare_extand_pages/custom-components/get_welfare_banner/get_welfare_goods/get_welfare_goods.js    2.74 kB      55  [emitted]         welfare_extand_pages/custom-components/get_welfare_banner/get_welfare_goods/get_welfare_goods
                            welfare_extand_pages/custom-components/get_welfare_banner/get_welfare_banner.js    1.63 kB      56  [emitted]         welfare_extand_pages/custom-components/get_welfare_banner/get_welfare_banner
                                      welfare_extand_pages/custom-components/activity-list/activity-list.js    1.98 kB      57  [emitted]         welfare_extand_pages/custom-components/activity-list/activity-list
                        welfare_extand_pages/custom-components/activity-description/activity-description.js  364 bytes      58  [emitted]         welfare_extand_pages/custom-components/activity-description/activity-description
                                                                         pages/welfare_home/welfare_home.js    12.1 kB      59  [emitted]         pages/welfare_home/welfare_home
                                                                            pages/welfare_home/item/item.js    2.49 kB      60  [emitted]         pages/welfare_home/item/item
                                                                                   pages/webview/webview.js  683 bytes      61  [emitted]         pages/webview/webview
                                                                                 pages/strategy/strategy.js    1.62 kB      62  [emitted]         pages/strategy/strategy
                                                               pages/strategy/components/service/service.js  458 bytes      63  [emitted]         pages/strategy/components/service/service
                                                               pages/strategy/components/problem/problem.js    1.37 kB      64  [emitted]         pages/strategy/components/problem/problem
                                                           pages/strategy/components/imageShow/imageShow.js  304 bytes      65  [emitted]         pages/strategy/components/imageShow/imageShow
                                                           pages/lottery_person_home/lottery_person_home.js    3.44 kB      66  [emitted]         pages/lottery_person_home/lottery_person_home
                                                                                   pages/fill_in/fill_in.js    4.38 kB      67  [emitted]         pages/fill_in/fill_in
                                               custom_components/visitor-blank-layer/visitor-blank-layer.js  421 bytes      68  [emitted]         custom_components/visitor-blank-layer/visitor-blank-layer
                                                       custom_components/vertion-control/vertion-control.js  674 bytes      69  [emitted]         custom_components/vertion-control/vertion-control
                                                                     custom_components/userinfo/userinfo.js  583 bytes      70  [emitted]         custom_components/userinfo/userinfo
                                                           custom_components/trophy_detail/trophy_detail.js  525 bytes      71  [emitted]         custom_components/trophy_detail/trophy_detail
                                             custom_components/prise-activity-alert/prise-activity-alert.js    1.21 kB      72  [emitted]         custom_components/prise-activity-alert/prise-activity-alert
                                                                   custom_components/posters-layer/index.js    8.93 kB      73  [emitted]         custom_components/posters-layer/index
                                                                         custom_components/navbar/navbar.js  894 bytes      74  [emitted]         custom_components/navbar/navbar
                                                     custom_components/layer-of-red-bag/layer-of-red-bag.js  846 bytes      75  [emitted]         custom_components/layer-of-red-bag/layer-of-red-bag
                                                         custom_components/layer-of-guide/layer-of-guide.js  771 bytes      76  [emitted]         custom_components/layer-of-guide/layer-of-guide
                                             custom_components/layer-of-cancel-bind/layer-of-cancel-bind.js  399 bytes      77  [emitted]         custom_components/layer-of-cancel-bind/layer-of-cancel-bind
                                     custom_components/join_welfare_group_entry/join_welfare_group_entry.js  634 bytes      78  [emitted]         custom_components/join_welfare_group_entry/join_welfare_group_entry
                                                             custom_components/group_detail/group_detail.js    2.77 kB      79  [emitted]         custom_components/group_detail/group_detail
                                                                 custom_components/car_select/car_select.js    3.42 kB      80  [emitted]         custom_components/car_select/car_select
                                                             custom_components/alphabet-nav/alphabet-nav.js    3.05 kB      81  [emitted]         custom_components/alphabet-nav/alphabet-nav
                                               collect_clues_pages/pages/select_car_info/select_car_info.js    2.92 kB      82  [emitted]         collect_clues_pages/pages/select_car_info/select_car_info
                                             collect_clues_pages/pages/recommend_series/recommend_series.js    7.34 kB      83  [emitted]         collect_clues_pages/pages/recommend_series/recommend_series
                                                 collect_clues_pages/pages/inquiry_result/inquiry_result.js    1.42 kB      84  [emitted]         collect_clues_pages/pages/inquiry_result/inquiry_result
                                                 collect_clues_pages/pages/evalute_result/evalute_result.js  740 bytes      85  [emitted]         collect_clues_pages/pages/evalute_result/evalute_result
                                                     collect_clues_pages/pages/collect_clue/collect_clue.js    5.32 kB      86  [emitted]         collect_clues_pages/pages/collect_clue/collect_clue
                                                                                                 common2.js     412 kB      87  [emitted]  [big]  common2
                                                                                      wxs/newEnergyType.wxs    1.05 kB          [emitted]         
                                                                                 images/bg_share_haibao.png    15.8 kB          [emitted]         
                                                                                             images/car.png    1.68 kB          [emitted]         
                                                                                           images/earth.png    5.08 kB          [emitted]         
                                                                              images/icon_empty_network.png     2.1 kB          [emitted]         
                                                                               images/icon_tab_1_normal.png  351 bytes          [emitted]         
                                                                             images/icon_tab_1_selected.png  355 bytes          [emitted]         
                                                                               images/icon_tab_2_normal.png  628 bytes          [emitted]         
                                                                             images/icon_tab_2_selected.png  740 bytes          [emitted]         
                                                                               images/icon_tab_3_normal.png  443 bytes          [emitted]         
                                                                             images/icon_tab_3_selected.png  429 bytes          [emitted]         
                                                                               images/icon_tab_4_normal.png  651 bytes          [emitted]         
                                                                             images/icon_tab_4_selected.png  649 bytes          [emitted]         
                                                                               images/img_poster_red_bg.png    4.48 kB          [emitted]         
                                                                                           images/wheel.png  434 bytes          [emitted]         
                                                                                       wxParse/wxParse.wxml    85.9 kB          [emitted]         
                                                                                       wxParse/wxParse.wxss    4.14 kB          [emitted]         
                                                                              components/article/index.wxml  563 bytes          [emitted]         
                                                                           components/helpdialog/index.wxml    1.66 kB          [emitted]         
                                                                           components/imagetoast/index.wxml  338 bytes          [emitted]         
                                                                            components/loading/loading.wxml    1.19 kB          [emitted]         
                                                                             components/loadmore/index.wxml  612 bytes          [emitted]         
                                                                                components/toast/index.wxml  146 bytes          [emitted]         
                                                                               components/tohome/index.wxml  390 bytes          [emitted]         
 [507] ./src/welfare_extand_pages/custom-components/layer-of-check-cancel-subscribe/layer-of-check-cancel-subscribe.js 463 bytes {44} [built]
 [536] ./src/welfare_extand_pages/pages/fill_info_success/fill_info_success.js 1.7 kB {16} [built]
 [537] ./src/welfare_extand_pages/pages/get_bounty/get_bounty.js 15.8 kB {15} [built]
 [538] ./src/welfare_extand_pages/pages/get_welfare/get_welfare.js 4.86 kB {14} [built]
 [539] ./src/welfare_extand_pages/pages/join-welfare-group/join-welfare-group.js 1.31 kB {13} [built]
 [540] ./src/welfare_extand_pages/pages/lottery_record/award_item/award_item.js 940 bytes {12} [built]
 [541] ./src/welfare_extand_pages/pages/lottery_record/history_item/history_item.js 929 bytes {11} [built]
 [542] ./src/welfare_extand_pages/pages/lottery_record/lottery_record.js 9.82 kB {10} [built]
 [543] ./src/welfare_extand_pages/pages/reward/reward.js 5.86 kB {9} [built]
 [544] ./src/welfare_extand_pages/pages/reward_list/reward_list.js 4.25 kB {8} [built]
 [545] ./src/welfare_extand_pages/pages/set_remind/set_remind.js 4.13 kB {7} [built]
 [546] ./src/welfare_extand_pages/pages/update_page/index.js 1.76 kB {6} [built]
 [547] ./src/welfare_extand_pages/pages/welfare_card_list/welfare_card_list.js 3.4 kB {5} [built]
 [548] ./src/welfare_extand_pages/pages/welfare_detail/welfare_detail.js 21.8 kB {4} [built]
 [628] multi ./src/app.json ./src/app.less ./src/pages/welfare_home/welfare_home.json ./src/pages/welfare_home/welfare_home.less ./src/pages/welfare_home/welfare_home.xml ./src/pages/lottery_person_home/lottery_person_home.json ./src/pages/lottery_person_home/lottery_person_home.less ./src/pages/lottery_person_home/lottery_person_home.xml ./src/pages/strategy/strategy.json ./src/pages/strategy/strategy.less ./src/pages/strategy/strategy.xml ./src/pages/fill_in/fill_in.json ./src/pages/fill_in/fill_in.less ./src/pages/fill_in/fill_in.xml ./src/pages/webview/webview.json ./src/pages/webview/webview.less ./src/pages/webview/webview.xml ./src/collect_clues_pages/pages/collect_clue/collect_clue.json ./src/collect_clues_pages/pages/collect_clue/collect_clue.less ./src/collect_clues_pages/pages/collect_clue/collect_clue.xml ./src/collect_clues_pages/pages/evalute_result/evalute_result.json ./src/collect_clues_pages/pages/evalute_result/evalute_result.less ./src/collect_clues_pages/pages/evalute_result/evalute_result.xml ./src/collect_clues_pages/pages/recommend_series/recommend_series.json ./src/collect_clues_pages/pages/recommend_series/recommend_series.less ./src/collect_clues_pages/pages/recommend_series/recommend_series.xml ./src/collect_clues_pages/pages/select_car_info/select_car_info.json ./src/collect_clues_pages/pages/select_car_info/select_car_info.less ./src/collect_clues_pages/pages/select_car_info/select_car_info.xml ./src/collect_clues_pages/pages/inquiry_result/inquiry_result.json ./src/collect_clues_pages/pages/inquiry_result/inquiry_result.less ./src/collect_clues_pages/pages/inquiry_result/inquiry_result.xml ./src/welfare_extand_pages/pages/welfare_detail/welfare_detail.json ./src/welfare_extand_pages/pages/welfare_detail/welfare_detail.less ./src/welfare_extand_pages/pages/welfare_detail/welfare_detail.xml ./src/welfare_extand_pages/pages/get_bounty/get_bounty.json ./src/welfare_extand_pages/pages/get_bounty/get_bounty.less ./src/welfare_extand_pages/pages/get_bounty/get_bounty.xml ./src/welfare_extand_pages/pages/fill_info/fill_info.json ./src/welfare_extand_pages/pages/fill_info/fill_info.less ./src/welfare_extand_pages/pages/fill_info/fill_info.xml ./src/welfare_extand_pages/pages/fill_info_success/fill_info_success.json ./src/welfare_extand_pages/pages/fill_info_success/fill_info_success.less ./src/welfare_extand_pages/pages/fill_info_success/fill_info_success.xml ./src/welfare_extand_pages/pages/cashback_apply/cashback_apply.json ./src/welfare_extand_pages/pages/cashback_apply/cashback_apply.less ./src/welfare_extand_pages/pages/cashback_apply/cashback_apply.xml ./src/welfare_extand_pages/pages/cashback_apply_success/cashback_apply_success.json ./src/welfare_extand_pages/pages/cashback_apply_success/cashback_apply_success.less ./src/welfare_extand_pages/pages/cashback_apply_success/cashback_apply_success.xml ./src/welfare_extand_pages/pages/lottery_record/lottery_record.json ./src/welfare_extand_pages/pages/lottery_record/lottery_record.less ./src/welfare_extand_pages/pages/lottery_record/lottery_record.xml ./src/welfare_extand_pages/pages/cashback_record/cashback_record.json ./src/welfare_extand_pages/pages/cashback_record/cashback_record.less ./src/welfare_extand_pages/pages/cashback_record/cashback_record.xml ./src/welfare_extand_pages/pages/reward/reward.json ./src/welfare_extand_pages/pages/reward/reward.less ./src/welfare_extand_pages/pages/reward/reward.xml ./src/welfare_extand_pages/pages/reward_list/reward_list.json ./src/welfare_extand_pages/pages/reward_list/reward_list.less ./src/welfare_extand_pages/pages/reward_list/reward_list.xml ./src/welfare_extand_pages/pages/base/base.json ./src/welfare_extand_pages/pages/base/base.less ./src/welfare_extand_pages/pages/base/base.xml ./src/welfare_extand_pages/pages/welfare_card_list/welfare_card_list.json ./src/welfare_extand_pages/pages/welfare_card_list/welfare_card_list.less ./src/welfare_extand_pages/pages/welfare_card_list/welfare_card_list.xml ./src/welfare_extand_pages/pages/get_welfare/get_welfare.json ./src/welfare_extand_pages/pages/get_welfare/get_welfare.less ./src/welfare_extand_pages/pages/get_welfare/get_welfare.xml ./src/welfare_extand_pages/pages/bounty_detail/bounty_detail.json ./src/welfare_extand_pages/pages/bounty_detail/bounty_detail.less ./src/welfare_extand_pages/pages/bounty_detail/bounty_detail.xml ./src/welfare_extand_pages/pages/update_page/index.json ./src/welfare_extand_pages/pages/update_page/index.less ./src/welfare_extand_pages/pages/update_page/index.xml ./src/welfare_extand_pages/pages/set_remind/set_remind.json ./src/welfare_extand_pages/pages/set_remind/set_remind.less ./src/welfare_extand_pages/pages/set_remind/set_remind.xml ./src/welfare_extand_pages/pages/fans_activity_record/fans_activity_record.json ./src/welfare_extand_pages/pages/fans_activity_record/fans_activity_record.less ./src/welfare_extand_pages/pages/fans_activity_record/fans_activity_record.xml ./src/welfare_extand_pages/pages/fans_activity_get/fans_activity_get.json ./src/welfare_extand_pages/pages/fans_activity_get/fans_activity_get.less ./src/welfare_extand_pages/pages/fans_activity_get/fans_activity_get.xml ./src/welfare_extand_pages/pages/fans_activity_detail/fans_activity_detail.json ./src/welfare_extand_pages/pages/fans_activity_detail/fans_activity_detail.less ./src/welfare_extand_pages/pages/fans_activity_detail/fans_activity_detail.xml ./src/welfare_extand_pages/pages/copy_own_code/copy_own_code.json ./src/welfare_extand_pages/pages/copy_own_code/copy_own_code.less ./src/welfare_extand_pages/pages/copy_own_code/copy_own_code.xml ./src/welfare_extand_pages/pages/join-welfare-group/join-welfare-group.json ./src/welfare_extand_pages/pages/join-welfare-group/join-welfare-group.less ./src/welfare_extand_pages/pages/join-welfare-group/join-welfare-group.xml ./src/pages/welfare_home/item/item.json ./src/pages/welfare_home/item/item.less ./src/pages/welfare_home/item/item.xml ./src/custom_components/visitor-blank-layer/visitor-blank-layer.json ./src/custom_components/visitor-blank-layer/visitor-blank-layer.less ./src/custom_components/visitor-blank-layer/visitor-blank-layer.xml ./src/custom_components/layer-of-red-bag/layer-of-red-bag.json ./src/custom_components/layer-of-red-bag/layer-of-red-bag.less ./src/custom_components/layer-of-red-bag/layer-of-red-bag.xml ./src/custom_components/join_welfare_group_entry/join_welfare_group_entry.json ./src/custom_components/join_welfare_group_entry/join_welfare_group_entry.less ./src/custom_components/join_welfare_group_entry/join_welfare_group_entry.xml ./src/custom_components/layer-of-guide/layer-of-guide.json ./src/custom_components/layer-of-guide/layer-of-guide.less ./src/custom_components/layer-of-guide/layer-of-guide.xml ./src/custom_components/layer-of-cancel-bind/layer-of-cancel-bind.json ./src/custom_components/layer-of-cancel-bind/layer-of-cancel-bind.less ./src/custom_components/layer-of-cancel-bind/layer-of-cancel-bind.xml ./src/pages/strategy/components/imageShow/imageShow.json ./src/pages/strategy/components/imageShow/imageShow.less ./src/pages/strategy/components/imageShow/imageShow.xml ./src/pages/strategy/components/service/service.json ./src/pages/strategy/components/service/service.less ./src/pages/strategy/components/service/service.xml ./src/pages/strategy/components/problem/problem.json ./src/pages/strategy/components/problem/problem.less ./src/pages/strategy/components/problem/problem.xml ./src/custom_components/vertion-control/vertion-control.json ./src/custom_components/vertion-control/vertion-control.less ./src/custom_components/vertion-control/vertion-control.xml ./src/custom_components/car_select/car_select.json ./src/custom_components/car_select/car_select.less ./src/custom_components/car_select/car_select.xml ./src/custom_components/alphabet-nav/alphabet-nav.json ./src/custom_components/alphabet-nav/alphabet-nav.less ./src/custom_components/alphabet-nav/alphabet-nav.xml ./src/custom_components/group_detail/group_detail.json ./src/custom_components/group_detail/group_detail.less ./src/custom_components/group_detail/group_detail.xml ./src/custom_components/posters-layer/index.json ./src/custom_components/posters-layer/index.less ./src/custom_components/posters-layer/index.wxml ./src/welfare_extand_pages/custom-components/more-welfare/more-welfare.json ./src/welfare_extand_pages/custom-components/more-welfare/more-welfare.less ./src/welfare_extand_pages/custom-components/more-welfare/more-welfare.xml ./src/welfare_extand_pages/custom-components/goods-item/goods-item.json ./src/welfare_extand_pages/custom-components/goods-item/goods-item.less ./src/welfare_extand_pages/custom-components/goods-item/goods-item.xml ./src/welfare_extand_pages/custom-components/activity-description/activity-description.json ./src/welfare_extand_pages/custom-components/activity-description/activity-description.less ./src/welfare_extand_pages/custom-components/activity-description/activity-description.xml ./src/welfare_extand_pages/custom-components/layer-of-null-card/layer-of-null-card.json ./src/welfare_extand_pages/custom-components/layer-of-null-card/layer-of-null-card.less ./src/welfare_extand_pages/custom-components/layer-of-null-card/layer-of-null-card.xml ./src/welfare_extand_pages/custom-components/layer-of-only-one/layer-of-only-one.json ./src/welfare_extand_pages/custom-components/layer-of-only-one/layer-of-only-one.less ./src/welfare_extand_pages/custom-components/layer-of-only-one/layer-of-only-one.xml ./src/welfare_extand_pages/custom-components/go-top-icon/go-top-icon.json ./src/welfare_extand_pages/custom-components/go-top-icon/go-top-icon.less ./src/welfare_extand_pages/custom-components/go-top-icon/go-top-icon.xml ./src/welfare_extand_pages/custom-components/layer-of-tao-key-success/layer-of-tao-key-success.json ./src/welfare_extand_pages/custom-components/layer-of-tao-key-success/layer-of-tao-key-success.less ./src/welfare_extand_pages/custom-components/layer-of-tao-key-success/layer-of-tao-key-success.xml ./src/welfare_extand_pages/custom-components/layer-of-check-order-status/layer-of-check-order-status.json ./src/welfare_extand_pages/custom-components/layer-of-check-order-status/layer-of-check-order-status.less ./src/welfare_extand_pages/custom-components/layer-of-check-order-status/layer-of-check-order-status.xml ./src/welfare_extand_pages/custom-components/layer-of-rule/layer-of-rule.json ./src/welfare_extand_pages/custom-components/layer-of-rule/layer-of-rule.less ./src/welfare_extand_pages/custom-components/layer-of-rule/layer-of-rule.xml ./src/welfare_extand_pages/custom-components/just-time/just-time.json ./src/welfare_extand_pages/custom-components/just-time/just-time.less ./src/welfare_extand_pages/custom-components/just-time/just-time.xml ./src/welfare_extand_pages/custom-components/guide/guide.json ./src/welfare_extand_pages/custom-components/guide/guide.less ./src/welfare_extand_pages/custom-components/guide/guide.xml ./src/welfare_extand_pages/custom-components/layer-of-limit-number/layer-of-limit-number.json ./src/welfare_extand_pages/custom-components/layer-of-limit-number/layer-of-limit-number.less ./src/welfare_extand_pages/custom-components/layer-of-limit-number/layer-of-limit-number.xml ./src/welfare_extand_pages/custom-components/layer-of-share/layer-of-share.json ./src/welfare_extand_pages/custom-components/layer-of-share/layer-of-share.less ./src/welfare_extand_pages/custom-components/layer-of-share/layer-of-share.xml ./src/welfare_extand_pages/custom-components/layer-of-creat-poster/layer-of-creat-poster.json ./src/welfare_extand_pages/custom-components/layer-of-creat-poster/layer-of-creat-poster.less ./src/welfare_extand_pages/custom-components/layer-of-creat-poster/layer-of-creat-poster.xml ./src/welfare_extand_pages/custom-components/layer-of-check-cancel-subscribe/layer-of-check-cancel-subscribe.json ./src/welfare_extand_pages/custom-components/layer-of-check-cancel-subscribe/layer-of-check-cancel-subscribe.less ./src/welfare_extand_pages/custom-components/layer-of-check-cancel-subscribe/layer-of-check-cancel-subscribe.xml ./src/welfare_extand_pages/custom-components/layer-of-add-customer/layer-of-add-customer.json ./src/welfare_extand_pages/custom-components/layer-of-add-customer/layer-of-add-customer.less ./src/welfare_extand_pages/custom-components/layer-of-add-customer/layer-of-add-customer.xml ./src/welfare_extand_pages/custom-components/layer-of-creat-poster-success/layer-of-creat-poster-success.json ./src/welfare_extand_pages/custom-components/layer-of-creat-poster-success/layer-of-creat-poster-success.less ./src/welfare_extand_pages/custom-components/layer-of-creat-poster-success/layer-of-creat-poster-success.xml ./src/welfare_extand_pages/custom-components/rank-and-strategy/rank-and-strategy.json ./src/welfare_extand_pages/custom-components/rank-and-strategy/rank-and-strategy.less ./src/welfare_extand_pages/custom-components/rank-and-strategy/rank-and-strategy.xml ./src/welfare_extand_pages/custom-components/go-home-icon/go-home-icon.json ./src/welfare_extand_pages/custom-components/go-home-icon/go-home-icon.less ./src/welfare_extand_pages/custom-components/go-home-icon/go-home-icon.xml ./src/custom_components/navbar/navbar.json ./src/custom_components/navbar/navbar.less ./src/custom_components/navbar/navbar.xml ./src/welfare_extand_pages/custom-components/layer-of-order-check/layer-of-order-check.json ./src/welfare_extand_pages/custom-components/layer-of-order-check/layer-of-order-check.less ./src/welfare_extand_pages/custom-components/layer-of-order-check/layer-of-order-check.xml ./src/welfare_extand_pages/custom-components/order-process/order-process.json ./src/welfare_extand_pages/custom-components/order-process/order-process.less ./src/welfare_extand_pages/custom-components/order-process/order-process.xml ./src/welfare_extand_pages/custom-components/layer-of-copy-orderid/layer-of-copy-orderid.json ./src/welfare_extand_pages/custom-components/layer-of-copy-orderid/layer-of-copy-orderid.less ./src/welfare_extand_pages/custom-components/layer-of-copy-orderid/layer-of-copy-orderid.xml ./src/welfare_extand_pages/custom-components/layer-of-select-order/layer-of-select-order.json ./src/welfare_extand_pages/custom-components/layer-of-select-order/layer-of-select-order.less ./src/welfare_extand_pages/custom-components/layer-of-select-order/layer-of-select-order.xml ./src/welfare_extand_pages/custom-components/layer-of-bind-taobao/layer-of-bind-taobao.json ./src/welfare_extand_pages/custom-components/layer-of-bind-taobao/layer-of-bind-taobao.less ./src/welfare_extand_pages/custom-components/layer-of-bind-taobao/layer-of-bind-taobao.xml ./src/welfare_extand_pages/custom-components/layer-of-cashback-status/layer-of-cashback-status.json ./src/welfare_extand_pages/custom-components/layer-of-cashback-status/layer-of-cashback-status.less ./src/welfare_extand_pages/custom-components/layer-of-cashback-status/layer-of-cashback-status.xml ./src/custom_components/userinfo/userinfo.json ./src/custom_components/userinfo/userinfo.less ./src/custom_components/userinfo/userinfo.xml ./src/welfare_extand_pages/pages/lottery_record/award_item/award_item.json ./src/welfare_extand_pages/pages/lottery_record/award_item/award_item.less ./src/welfare_extand_pages/pages/lottery_record/award_item/award_item.xml ./src/welfare_extand_pages/pages/lottery_record/history_item/history_item.json ./src/welfare_extand_pages/pages/lottery_record/history_item/history_item.less ./src/welfare_extand_pages/pages/lottery_record/history_item/history_item.xml ./src/custom_components/trophy_detail/trophy_detail.json ./src/custom_components/trophy_detail/trophy_detail.less ./src/custom_components/trophy_detail/trophy_detail.xml ./src/welfare_extand_pages/custom-components/unverified/unverified.json ./src/welfare_extand_pages/custom-components/unverified/unverified.less ./src/welfare_extand_pages/custom-components/unverified/unverified.xml ./src/welfare_extand_pages/custom-components/official_customer_service_entry/official_customer_service_entry.json ./src/welfare_extand_pages/custom-components/official_customer_service_entry/official_customer_service_entry.less ./src/welfare_extand_pages/custom-components/official_customer_service_entry/official_customer_service_entry.xml ./src/welfare_extand_pages/custom-components/welfare_card_item/welfare_card_item.json ./src/welfare_extand_pages/custom-components/welfare_card_item/welfare_card_item.less ./src/welfare_extand_pages/custom-components/welfare_card_item/welfare_card_item.xml ./src/welfare_extand_pages/custom-components/get_welfare_banner/get_welfare_banner.json ./src/welfare_extand_pages/custom-components/get_welfare_banner/get_welfare_banner.less ./src/welfare_extand_pages/custom-components/get_welfare_banner/get_welfare_banner.xml ./src/welfare_extand_pages/custom-components/get_welfare_banner/get_welfare_progress/get_welfare_progress.json ./src/welfare_extand_pages/custom-components/get_welfare_banner/get_welfare_progress/get_welfare_progress.less ./src/welfare_extand_pages/custom-components/get_welfare_banner/get_welfare_progress/get_welfare_progress.xml ./src/welfare_extand_pages/custom-components/get_welfare_banner/get_welfare_people/get_welfare_people.json ./src/welfare_extand_pages/custom-components/get_welfare_banner/get_welfare_people/get_welfare_people.less ./src/welfare_extand_pages/custom-components/get_welfare_banner/get_welfare_people/get_welfare_people.xml ./src/welfare_extand_pages/custom-components/get_welfare_banner/get_welfare_alert/get_welfare_alert.json ./src/welfare_extand_pages/custom-components/get_welfare_banner/get_welfare_alert/get_welfare_alert.less ./src/welfare_extand_pages/custom-components/get_welfare_banner/get_welfare_alert/get_welfare_alert.xml ./src/welfare_extand_pages/custom-components/get_welfare_banner/get_welfare_goods/get_welfare_goods.json ./src/welfare_extand_pages/custom-components/get_welfare_banner/get_welfare_goods/get_welfare_goods.less ./src/welfare_extand_pages/custom-components/get_welfare_banner/get_welfare_goods/get_welfare_goods.xml ./src/welfare_extand_pages/custom-components/activity-list/activity-list.json ./src/welfare_extand_pages/custom-components/activity-list/activity-list.less ./src/welfare_extand_pages/custom-components/activity-list/activity-list.xml ./src/custom_components/prise-activity-alert/prise-activity-alert.json ./src/custom_components/prise-activity-alert/prise-activity-alert.less ./src/custom_components/prise-activity-alert/prise-activity-alert.xml 3.1 kB {0} [built]
    + 614 hidden modules
Done in 14.60s.
Initializing...
idePortFile: /Users/duncy/Library/Application Support/微信web开发者工具/Default/.ide
IDE server has started, listening on http://127.0.0.1:24223
initialization finished
uploading project...

upload success
200
返回状态码200，登录成功！
Email was triggered for: Always
Email was triggered for: Success
Sending email for trigger: Always
Sending email to: hemingjie@youcheyihou.com zhangyanyong@youcheyihou.com liuzuoxing@youcheyihou.com
Sending email for trigger: Success
An attempt to send an e-mail to empty list of recipients, ignored.
Finished: SUCCESS